"""Sửa bảng

Revision ID: f70521e03857
Revises: d818c5ca338a
Create Date: 2025-05-07 23:16:14.176581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70521e03857'
down_revision: Union[str, None] = 'd818c5ca338a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['name'])
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['teacher_id'], ['id'])
    op.drop_column('course', 'user_id')
    op.add_column('lesson', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('lesson', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('lesson', 'video_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'lesson', 'user', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.alter_column('lesson', 'video_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('lesson', 'teacher_id')
    op.drop_column('lesson', 'created_at')
    op.add_column('course', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
